apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogo-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc.oficina-ns.svc.cluster.local:5432/catalogo_db"
  SPRING_DATASOURCE_USERNAME: "userCatalogoDb"
