apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "catalogo_db"
  POSTGRES_USER: "userCatalogoDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogo-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://academico-rds.cpu6wek2azm8.us-east-1.rds.amazonaws.com:5432/catalogo_db"
  SPRING_DATASOURCE_USERNAME: "userCatalogoDb"
  ENV_NAME: "local"
