apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - catalogo-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml

namePrefix: catalogo-
namespace: oficina-ns
